version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_pool_data:/bitnami/postgresql
volumes:
  pg_pool_data: